### ISSUE TITLE
Unable to find module 'index'

### ISSUE THREAD

**Issue by josephrussell** [mackenziestarr/deathproof#1]
Node 6.2.2

$ node ./node_modules/deathproof/ --host 127.0.0.1:8000 --file varnish.log --format common

Error: Cannot find module 'index'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/deathproof/test.js:3:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by josephrussell** [comment]
Got it to work with 
var runner = require('.');
